import ReduxProvider from "@/redux/Provider";

import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`w-screen min-h-screen relative`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
